services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile.httpd
    container_name: phalcon-study-httpd
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: phalcon-study-php
    volumes:
      - ./:/var/www/html